apiVersion: apps/v1

kind: Deployment

metadata:

  name: python-flask-server
  namespace: example

  labels:

    app: test-flask

spec:

  replicas: 1

  selector:

    matchLabels:

      app: test-flask

  template:

    metadata:

      labels:

        app: test-flask

    spec:

      containers:

      - name: cont1

        image: pujithamuttineni/flask-python:example

        ports:

        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: example
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
